### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by wo80**
Update project structure, convert project files to netstandard2.0 and net6.0, fixes some known issues.

Update readme and explain license issues.

### CODE REVIEW

**Comment by Geri-Borbas** [comment]
Nice update!
Can't you merge it yourself?

I belive I transferred all the rights to do that (no way for me to review the changeset anyway 😄).

**Comment by wo80** [comment]
> Nice update!

Thanks.
> Can't you merge it yourself?

Sure I can, but I might add more commits. That's why I added WIP = work in progress = do not merge 😉

**Comment by wo80** [comment]
> no way for me to review the changeset anyway

As a collaborator you should be able to review, shouldn't you? Or would I have to add you explicitly?

**Comment by Geri-Borbas** [comment]
Sure I can see the code, I meant that I can't really comprehend the internals anyway. 😅 If you think it is too WIP now, then just leave it in `develop` I guess (that is what that branch is made for after all). Adventurous people can use that anyway.

**Comment by Geri-Borbas** [comment]
Oh, wow, you made file clean-ups as well with source files only. 🙌 It makes the `Release` branch obsolete as well.

Still, I think people would love to use it with your recent add-ons: just call it beta 5, and merge it. 😆

**Comment by wo80** [comment]
Just wanted to leave a sign that some changes are pending. I think I'll merge this within the next week.

BTW: the `Fix/Unity-fixes` branch can be removed, right?

**Comment by wo80** [comment]
I've never used submodules on Github, so maybe the Release branch could still be useful
(not having the dependency on net6.0-**windows**).

**Comment by Geri-Borbas** [comment]
Sure, remove that as well, just leave `develop` and a `master`.

The Unity fix branch is really just a couple of changes to suppress some warnings that only Unity compiler raised at 2017 time. Seemingly people do their own compiler/warning fixes anyway: https://github.com/wo80/Triangle.NET/network

Perhaps someone can jump in who is using it for Unity in the present. As far as I recall, this is the only library that can do proper polygon clipping, triangulation, and the like.

**Comment by Geri-Borbas** [comment]
> I've never used submodules on Github, so maybe the Release branch could still be useful (not having the dependency on net6.0-**windows**).

I think people can simply use the new `master` as the submodule branch (given all the cleanup you made).

**Comment by wo80** [comment]
Yeah, not having to keep a rather unrelated branch up to date is a plus, so I shouldn't worry too much about the sub module usage.

**Pull request merged**
